baseURL = "https://example.org/"
languageCode = "en-us"
title = "Alexander Blatchford's Epic Website and Mitch's Sack of Potatoes"
theme = "ananke"
[params]
  subtitle = "A guy who does some things"
  [params.contact]
    email = "alexander.blatchford@gmail.com"